#!/bin/bash

. /etc/rc.conf
. ~/etc/rc.d/functions

PID=`pidof -o %PPID dzen_python`
case "$1" in
  start)
    stat_busy "Starting Dzen2 Python Script"
    [ -z "$PID" ] && /home/chad/.dzen/bin/dzen_config.py&
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon dzend
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Dzen2 Python Script"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      [ -f ~/tmp/var/run/dzend.pid ] && rm ~/tmp/var/run/dzend.pid
      rm_daemon dzend
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
